package com.arranger.apv.event;

public enum EventTypes {
	SETUP, DRAW, SPARK, CARNIVAL, STAR, STROBE, SCENE_COMPLETE, 
	COMMAND_INVOKED, APV_CHANGE, TWIRL, LOCATION, RANDOM_MESSAGE,
	MARQUEE, EARTHQUAKE, WATERMARK, COLOR_CHANGE,
}