package com.arranger.apv.event;

public enum EventTypes {
	SETUP, DRAW, K_SCOPE, SPARK, CARNIVAL, STAR, STROBE, SCENE_COMPLETE, SETLIST_COMPLETE,
	COMMAND_INVOKED, APV_CHANGE, TWIRL, LOCATION, RANDOM_MESSAGE,
	MARQUEE, EARTHQUAKE, WATERMARK, COLOR_CHANGE, SONG_START, SET_PACK_START, ALDA
}